name = "Inkspire"
description = "A classic blog theme for modern developers"
# An optional tags to allow quick search
tags = ["blog", "developer", "design", "modern", "responsive", "minimal", "minimalistic"]
license = "CC-BY-NC-SA-4.0"
homepage = "https://github.com/josegarcia/inkspire"
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Jose Garcia"
homepage = "https://josegarcia.dev"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
